first draft to get comments and reviews
frantizek/github-profile-achievements pull request #9
Opened 2023-07-25 17:11 UTC by frantizek

2023-09-11 23:22 UTC, cibervicho requested changes
Tsss, un poquito de contexto. Podrías agregar un poco de documentación o comentarios para darme una idea de que se trata?

2023-09-11 23:32 UTC, frantizek commented
creo que el principal contexto es el README

https://github.com/frantizek/CSF_xtractor#readme

2023-09-12 03:24 UTC, cibervicho commented
> creo que el principal contexto es el README
> 
> https://github.com/frantizek/CSF_xtractor#readme

Sorry, no sabia de este README. Fue mi culpa al no leerlo

2023-09-12 03:39 UTC, cibervicho requested changes
En general muy bien. Quiero probarlo luego.

2023-09-12 03:39 UTC, cibervicho commented on main.py
> +CFDI_4 = {
Solo es una duda, estos son los códigos en el SAT que corresponden a cada situación fiscal? Interesante...

2023-09-12 03:39 UTC, cibervicho commented on main.py
> +    def save_convert_pdf_to_txt(self):
Esta función parece que no se usa en tu código.

2023-09-12 03:39 UTC, cibervicho commented on main.py
> +    parser = argparse.ArgumentParser(description=
Que chido que estés usando argumentos en tu programa.

2023-09-12 03:39 UTC, cibervicho commented on main.py
> +            #     print(text)
Te recomiendo que limpies tu código de todo el código comentado. Se ve mas limpio y cuesta menos revisarlo.

2023-09-12 03:39 UTC, cibervicho commented on main.py
> +def main():
En general, tu función main es extremadamente grande. Yo te recomiendo que veas como puedes abstraer secuencias de comandos y mejor crear mas funciones pequeñas que hagan ese trabajo, para que el flujo principal sea mas ordenado y entendible. Al final te va a ser de utilidad para mantener el código.

2023-09-12 03:39 UTC, cibervicho commented on main.py
> +        print("Target directory or file doesn't exist")
Elige un idioma para comunicar errores, warnings o simples comentarios al usuario.

2023-09-12 03:39 UTC, cibervicho commented on requirements.txt
> +pdfminer==20191125
Este es el único requerimiento que tiene tu programa? Parece que si.

2023-09-12 04:08 UTC, frantizek commented on main.py
> +CFDI_4 = {
Correcto. Este diccionario lo estoy usando para que cuando un tipo de situación fiscal aparece en la constancia, lo puedas usar con el número que tiene para el SAT.
Incluso puse en las pruebas mi CSF y si lo muestra.
Dato aún más curioso: una persona física o moral puede estar activo en varios regímenes. Ese caso puede ser más complejo pero no lo agregue a la validación.

2023-09-12 04:09 UTC, cibervicho commented on main.py
> +CFDI_4 = {
Ah caray, cuales pruebas. No vi nungún archivo de pruebas. Como las ejecutas?

2023-09-12 04:11 UTC, frantizek commented on main.py
> +    def save_convert_pdf_to_txt(self):
Aquí llega el momento de una terrible confesión. Estuve usando otra librería para leer el PDF pero entre los caracteres mal leídos y distribuidos aún peor, era demasiado complejo extraer los datos.
Así que esta clase completa es un copy / paste porque termino siendo el único método con que pude extraerlo. 
_Shame on me_

2023-09-12 04:12 UTC, frantizek commented on main.py
> +    def save_convert_pdf_to_txt(self):
TODO : Eliminar la función.

Aunque luego pienso en esa frase que dice: 

Si ya funciona, ya ni le muevas.

2023-09-12 04:14 UTC, frantizek commented on main.py
> +def main():
TODO: 

Identificar el flujo de los datos para descomponer main en funciones.

2023-09-12 04:16 UTC, frantizek commented on main.py
> +            #     print(text)
**_TODO:_**

Limpieza de código comentado

2023-09-12 04:19 UTC, frantizek commented on main.py
> +        print("Target directory or file doesn't exist")
De acuerdo.

Duda:

Si llegan a usar el script, creo que sería mejo dejar toda la información que despliega al usuario en español.

Pero ¿también cambiarías todos los comentarios internos y/o documentación?

2023-09-12 04:21 UTC, frantizek commented on requirements.txt
> +pdfminer==20191125
Pues es el único fuera de lo "normal".

El resto de los imports son más estándar...

2023-09-12 04:23 UTC, frantizek commented on main.py
> +CFDI_4 = {
Ah, no tengo como tal pruebas o set de pruebas aún en mente. 
Pensaba agregar como una siguiente fase.

Me refería a pruebas manuales o locales mientras iba haciendo el desarrollo.

2023-09-13 05:34 UTC, cibervicho commented on main.py
> +        print("Target directory or file doesn't exist")
Si, creo que si optaría por seguir con un mismo idioma.

2023-09-13 05:37 UTC, cibervicho commented on main.py
> +def main():
https://github.com/frantizek/CSF_xtractor/issues/10

2023-09-13 05:37 UTC, cibervicho commented on main.py
> +            #     print(text)
https://github.com/frantizek/CSF_xtractor/issues/11

2023-09-13 05:40 UTC, cibervicho commented on main.py
> +    def save_convert_pdf_to_txt(self):
Si funciona, pero si la eliminas debe seguir funcionando 😅
https://github.com/frantizek/CSF_xtractor/issues/12

2023-09-13 06:01 UTC, cibervicho requested changes
Si ya me conoces... para que me invitas? 😁

2023-09-13 06:01 UTC, cibervicho commented on dnt_consecutivo_latest.txt
> +1000
Pura curiosidad, para que sirve este número consecutivo?

2023-09-13 06:01 UTC, cibervicho commented on main.py
> +    datos_csf['codigo'] = "dnt" + str(numero)
Que significa el prefijo "dnt"?

2023-09-13 06:01 UTC, cibervicho commented on main.py
> +    datos_csf['codigo'] = "dnt" + str(numero)
No he revisado todos los campos de `datos_csf` (y ni lo voy a hacer, pero al menos `datos_csf['codigo']` no se usa nunca. Cual es su propósito?
Pregunto porque aquí es donde guardas el número consecutivo del archivo dnt_consecutivo_latest.txt, que al parecer solo lo estás decrementando, pero sin ningún propósito aparente. Al menos a mi entendimiento. 😕

2023-09-13 06:01 UTC, cibervicho commented on main.py
> +class bcolors:
Tu código empieza a incrementarse cada vez mas.
Plis, crea una carpeta nueva de 'utilerias' y guarda ahí este tipo de clases, constantes, y demás funciones y monerías que utilices en el proyecto pero que no tienen relevancia propia de la funcionalidad del proyecto, para que esté mejor modularizado.

2023-09-13 06:01 UTC, cibervicho commented on main.py
> +def get_info(path):
Esta función, por ejemplo, es buena candidata para estar dentro de 'utilerias'

2023-09-13 06:01 UTC, cibervicho commented on main.py
> +def extraer_numero_consecutivo(archivo):
Como en otro comentario, no entiendo la utilidad de extraer el contenido numérico en un archivo, cuando ese código no se utiliza (por ahora, y a mi parecer). Falta documentación je je je

Esta función, por ejemplo, es buena candidata para estar dentro de 'utilerias'

2023-09-13 06:01 UTC, cibervicho commented on main.py
> +def decrementar_numero(numero):
Como en otro comentario, no entiendo la utilidad de decrementar el contenido numérico en un archivo, cuando ese código no se utiliza (por ahora, y a mi parecer). Falta documentación je je je

Esta función, por ejemplo, es buena candidata para estar dentro de 'utilerias'

2023-09-13 06:01 UTC, cibervicho commented on main.py
> +def guardar_numero(archivo, numero):
Como en otro comentario, no entiendo la utilidad de guardar el contenido numérico en un archivo, cuando ese código no se utiliza (por ahora, y a mi parecer). Falta documentación je je je

Esta función, por ejemplo, es buena candidata para estar dentro de 'utilerias'

2023-09-13 06:01 UTC, cibervicho commented on main.py
> +def eliminar_elementos_vacios_y_con_pagina(lista):
Esta función, por ejemplo, es buena candidata para estar dentro de 'utilerias'

2023-09-13 06:01 UTC, cibervicho commented on main.py
> +def extract_info_from_pdf(current_CSF):
Yo optaría por incluir esta función dentro de la clase. Esto implica refactorizar el código, pero tiene mas sentido.

2023-09-13 06:01 UTC, cibervicho commented on requirements.txt
> +pdfminer==20191125
Duda: Cómo haces tu desarrollo? Utilizas ambientes virtuales y ahí instalas tus dependencias? o instalas todas tus dependencias directamente en el Sistema Operativo, y de ahí comienzas a desarrollar?
Te pregunto, porque si usas ambientes virtuales, tan fácil como ejecutar un `pip freeze > requirements.txt` es suficiente para mantener este archivo con todo lo que tu proyecto necesita cada vez que usas una librería no standard, y mantienes tu Sistema Operativo limpio.

2023-09-13 14:50 UTC, frantizek commented on dnt_consecutivo_latest.txt
> +1000
es un campo que tiene la herramienta esta de factupronto, es un identificador unico que la verdad no le veo mucho sentido, pero como es parte de los campos requeridos pues, lo agregue.
Originalmente lo habia implementado como un numero random entre 1000 y 9999, pero pues aun asi habia posibilidades de que se repitiera...

2023-09-13 14:50 UTC, frantizek commented on main.py
> +    datos_csf['codigo'] = "dnt" + str(numero)
es Dinastia segun yo sin las vocales, pero me acabo de dar cuenta que es tambien sin la S y es un identificador que invente para que no fuera solo el numero.

2023-09-13 14:53 UTC, frantizek commented on main.py
> +    datos_csf['codigo'] = "dnt" + str(numero)
dentro de la parte de extraerlo, no, no se usa, pero al ser un campo requerido para cuando quieres agregar un nuevo "cliente" en la plataforma de factupronto, es por eso que lo estoy agregando.

2023-09-13 14:55 UTC, frantizek commented on requirements.txt
> +pdfminer==20191125
ahorita lo que he estado utilizando son los codespaces de github.

2023-09-13 15:09 UTC, cibervicho commented on dnt_consecutivo_latest.txt
> +1000
Entiendo. Ahora tiene sentido.

2023-09-13 15:10 UTC, cibervicho commented on main.py
> +    datos_csf['codigo'] = "dnt" + str(numero)
Entendido. Gracias por la clarificación.

2023-09-13 15:14 UTC, cibervicho commented on main.py
> +def extraer_numero_consecutivo(archivo):
Queda claro el propósito de esta función. De todas formas queda pendiente la parte de que es buena candidata para estar dentro de 'utilerias'

2023-09-13 15:14 UTC, cibervicho commented on main.py
> +def decrementar_numero(numero):
Queda claro el propósito de esta función. De todas formas queda pendiente la parte de que es buena candidata para estar dentro de 'utilerias'

2023-09-13 15:14 UTC, cibervicho commented on main.py
> +def guardar_numero(archivo, numero):
Queda claro el propósito de esta función. De todas formas queda pendiente la parte de que es buena candidata para estar dentro de 'utilerias'

2023-09-13 15:16 UTC, cibervicho commented on requirements.txt
> +pdfminer==20191125
No se como funcionan. Son ambientes virtuales que te proporciona Github? Son ambientes virtuales que no existen en tu computadora? Toda la codificación se realiza en la nube?

2023-09-13 15:18 UTC, cibervicho requested changes
No creo que sea necesaria otra revisión, sino hasta que se resuelvan los comentarios que quedan abiertos.

2023-09-13 17:29 UTC, frantizek commented
> No creo que sea necesaria otra revisión, sino hasta que se resuelvan los comentarios que quedan abiertos.

Los comentarios han sido contestados y se han creado los issues para trabajar a futuro.

Cuando tengas oportunidad revisas.

2023-09-13 20:19 UTC, cibervicho approved these changes
Se realizaron varios reviews, y como bien se comenta, existen varios issues creados para resolver en próximos commits.
Adelante con el merge inicial.

2023-09-13 20:21 UTC, merged